# Generated by Django 3.2.13 on 2022-04-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviesrest',
            options={'ordering': ['-year', '-rating'], 'verbose_name': 'show'},
        ),
    ]
