# Generated by Django 3.2.13 on 2022-04-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesrest',
            name='count',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
