# Generated by Django 3.2.13 on 2022-04-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviesrest_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviesrest',
            options={'ordering': ['-year', '-rating'], 'verbose_name': 'Movie'},
        ),
        migrations.AlterField(
            model_name='moviesrest',
            name='show_id',
            field=models.IntegerField(unique=True),
        ),
    ]
